In [9]:
import torch
from torch_scatter import scatter_add

# scatter 
src = torch.Tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
out = src.new_zeros((2, 6))

out, argmax = scatter_add(src, index, out=out)

print(out)

tensor([0., 0., 4., 3., 3., 0.])


In [10]:
print(argmax)

tensor([2., 4., 4., 0., 0., 0.])


In [12]:
a = torch.tensor([3, 2, 1])
b = torch.tensor([5, 3, 9])
torch.cat([a , b])

tensor([3, 2, 1, 5, 3, 9])